### ISSUE TITLE
build error on ubuntu 17.04

### ISSUE THREAD

**Issue by pr0gr4m** [madmantm/rtl8814au#2]
I try to build on Ubuntu 17.04 but it failed with following error message

/home/pr0gr4m/git/rtl8814au/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_add_monitor_if’:
/home/pr0gr4m/git/rtl8814au/os_dep/linux/ioctl_cfg80211.c:3962:10: error: ‘struct net_device’ has no member named ‘priv_destructor’; did you mean ‘destructor’?
  mon_ndev->priv_destructor = rtw_ndev_destructor;
          ^~
scripts/Makefile.build:294: recipe for target '/home/pr0gr4m/git/rtl8814au/os_dep/linux/ioctl_cfg80211.o' failed

How I can fix that problem?

**Comment by pr0gr4m** [comment]
https://github.com/madmantm/rtl8814au/pull/4/commits/50c7e4025ceb06f75602347358ec7304b5b4ee6c
